<!doctype html>
<head>
    <title>${title}</title>
    <link rel="stylesheet" href="source/style.css">
    <meta charset="${charset}">
</head>

<body>
    <header>
        <h1>${title}</h1>
        <div class="actions">
            <#--action menu-->
        </div>
    </header>
    <section class="main">
        <#--main context-->
    </section>
    <footer>
        footer
    </footer>
</body>
</html>